{
  "hash": "b64c7be2c9df00094bc68d95fa5ffd29",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Iniciación al estudio de sistemas dinámicos discretos\nlang: es\njupyter: julia-1.12\n---\n\nUn **sistema dinámico discreto** viene dado por una ecuación en diferencias\n\n$$\nx_{n+1} = f(x_n),\n$$\n\nque genera la órbita $x_0, x_1 = f(x_0), x_2 = f(x_1),\\dots$ Los **puntos fijos** son las soluciones de $f(x^*) = x^*$; un punto fijo es estable si $|f'(x^*)| < 1$ e inestable si $|f'(x^*)| > 1$. Estos sistemas presentan una fenomenología muy rica —duplicaciones de periodo y caos— aun con reglas $f$ sencillas.\n\n## Ejercicios resueltos\n\nPara la realización de esta práctica se requieren los siguientes paquetes:\n\n```julia\nusing SymPyPythonCall  # Cálculo simbólico de puntos fijos.\nusing Plots            # Dibujo de gráficas.\nusing LaTeXStrings     # Código LaTeX en los gráficos.\n```\n\n\n\n:::{.callout-note collapse=\"true\"}\n## Versiones de Julia y de los paquetes utilizados\n\n::: {.content-visible unless-format=\"pdf\"}\n\n::: {#12741260 .cell execution_count=3}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=4}\n![](https://img.shields.io/badge/Julia-1.12.6-9558B2?logo=julia)\n\n:::\n:::\n\n\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n\n::: {#0e970c4d .cell execution_count=4}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=5}\n**Versión de Julia:** 1.12.6\n\n:::\n:::\n\n\n:::\n\n\n::: {#588cea10 .cell execution_count=6}\n\n::: {.cell-output .cell-output-stdout}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre><span class=\"ansi-green-fg ansi-bold\">Status</span> `~/.julia/environments/v1.12/Project.toml`\n\n  <span class=\"ansi-bright-black-fg\">[b964fa9f] </span>LaTeXStrings v1.4.0\n\n  <span class=\"ansi-bright-black-fg\">[91a5bcdd] </span>Plots v1.41.6\n\n  <span class=\"ansi-bright-black-fg\">[bc8888f7] </span>SymPyPythonCall v0.5.1\n</pre>\n```\n:::\n\n:::\n:::\n\n\n\n:::\n\n\n\nFunción auxiliar para generar órbitas.\n\n::: {#46245e23 .cell execution_count=8}\n``` {.julia .cell-code}\nfunction orbita(f, x0, n)\n    xs = zeros(n + 1)\n    xs[1] = x0\n    for i in 1:n\n        xs[i+1] = f(xs[i])\n    end\n    xs\nend;\n```\n:::\n\n\n:::{#exr-interes-compuesto}\n**Interés compuesto y amortización (finanzas).** Un préstamo de $C_0 = 20.000$ € a un interés mensual del $r = 0.5\\%$ del que se pagan cuotas fijas de $p = 400$ € al mes evoluciona según\n\n$$\nC_{n+1} = (1 + r)\\,C_n - p = 1.005\\,C_n - 400.\n$$\n\na.  Hallar el punto fijo del sistema e interpretarlo. ¿Es estable?\n\n    :::{.callout-note collapse=\"true\"}\n    ## Ayuda\n    El punto fijo cumple $C^* = 1.005\\,C^* - 400$. Para una recta $f(C) = aC + b$, la estabilidad depende de $|a|$.\n    :::\n\n    :::{.callout-tip collapse=\"true\"}\n    ## Solución\n\n\n    ::: {#bb970517 .cell execution_count=9}\n    ``` {.julia .cell-code}\n    using SymPyPythonCall\n    @syms C\n    Cfijo = solve(Eq(1.005C - 400, C), C)[1]\n    ```\n    \n    ::: {.cell-output .cell-output-display .cell-output-markdown execution_count=10}\n    $80000.0$\n    :::\n    :::\n    \n    \n    El punto fijo es $C^* = 80\\,000$ €: es el saldo para el que los intereses ($0.005\\cdot 80000 = 400$) igualan exactamente la cuota, de modo que la deuda no cambiaría. Como la pendiente es $a = 1.005 > 1$, el punto fijo es **inestable**: si la deuda inicial es menor que 80 000 €, decrece hasta amortizarse; si fuera mayor, crecería sin control.\n    :::\n\na.  Iterar el sistema y calcular en cuántos meses se cancela el préstamo. Dibujar la evolución del saldo.\n\n    :::{.callout-tip collapse=\"true\"}\n    ## Solución\n\n\n    ::: {#1ae2d3c3 .cell execution_count=10}\n    ``` {.julia .cell-code}\n    f(C) = 1.005C - 400\n    saldos = orbita(f, 20000.0, 60)\n    n_cancela = findfirst(<=(0), saldos) - 1\n    ```\n    \n    ::: {.cell-output .cell-output-display execution_count=11}\n    ```\n    58\n    ```\n    :::\n    :::\n    \n    \n\n    ::: {#9df1b4c7 .cell execution_count=11}\n    ``` {.julia .cell-code}\n    using Plots\n    plot(0:length(saldos)-1, saldos, marker = :circle, ms = 3, lw = 1.5,\n        legend = false, xlab = \"Mes\", ylab = \"Saldo (€)\")\n    hline!([0], color = :black)\n    ```\n    \n    ::: {.cell-output .cell-output-display execution_count=12}\n    ![](06-sistemas-dinamicos-discretos_files/figure-html/cell-12-output-1.svg){}\n    :::\n    :::\n    \n    \n    El préstamo se cancela en unos **58 meses** (algo menos de 5 años). El último mes la cuota es menor que 400 €.\n    :::\n:::\n\n:::{#exr-cobweb-logistica}\n**Diagrama de telaraña del modelo logístico.** El modelo logístico discreto de una población normalizada es\n\n$$\nx_{n+1} = r\\,x_n(1 - x_n),\n$$\n\nque para valores moderados de $r$ tiene un punto fijo estable.\n\na.  Para $r = 2.8$, calcular los puntos fijos, su estabilidad y dibujar el **diagrama de telaraña** (cobweb) mostrando la convergencia al equilibrio.\n\n    :::{.callout-note collapse=\"true\"}\n    ## Ayuda\n    Los puntos fijos son $x^* = 0$ y $x^* = 1 - 1/r$. El diagrama de telaraña alterna movimientos verticales hasta la curva $y = f(x)$ y horizontales hasta la diagonal $y = x$.\n    :::\n\n    :::{.callout-tip collapse=\"true\"}\n    ## Solución\n\n\n    ::: {#a50b2b73 .cell execution_count=12}\n    ``` {.julia .cell-code}\n    @syms x r\n    using SymPyPythonCall\n    puntos = solve(Eq(r * x * (1 - x), x), x)\n    ```\n    \n    ::: {.cell-output .cell-output-display .cell-output-markdown execution_count=13}\n    $\\left[\\begin{smallmatrix}0\\\\\\frac{r - 1}{r}\\end{smallmatrix}\\right]$\n    :::\n    :::\n    \n    \n\n    ::: {#28bd4d0d .cell execution_count=13}\n    ``` {.julia .cell-code}\n    r0 = 2.8\n    derivada = diff(r * x * (1 - x), x)\n    [(N(p.subs(r, r0)), N(abs(derivada.subs(Dict(x => p, r => r0))))) for p in puntos]\n    ```\n    \n    ::: {.cell-output .cell-output-display execution_count=14}\n    ```\n    2-element Vector{Tuple{Real, Number}}:\n     (0, 2.8)\n     (0.6428571428571428, Abs(2.8 - 5.6*(r - 1)/r))\n    ```\n    :::\n    :::\n    \n    \n    Para $r=2.8$: $x^*=0$ tiene $|f'|=2.8>1$ (inestable) y $x^*=1-1/2.8\\approx 0.643$ tiene $|f'|=|2-r|=0.8<1$ (**estable**). Dibujamos la telaraña:\n\n\n    ::: {#4ec78fdd .cell execution_count=14}\n    ``` {.julia .cell-code}\n    using Plots, LaTeXStrings\n    function cobweb(f, x0, n; kw...)\n        plt = plot(f, 0, 1, lw = 2, label = L\"y=f(x)\", aspect_ratio = :equal; kw...)\n        plot!(plt, identity, 0, 1, lw = 1.5, ls = :dash, label = L\"y=x\")\n        x = x0\n        for _ in 1:n\n            y = f(x)\n            plot!(plt, [x, x], [x, y], color = :gray, label = \"\")\n            plot!(plt, [x, y], [y, y], color = :gray, label = \"\")\n            x = y\n        end\n        plt\n    end\n    cobweb(x -> 2.8x * (1 - x), 0.1, 30, xlab = L\"x_n\", ylab = L\"x_{n+1}\")\n    ```\n    \n    ::: {.cell-output .cell-output-display execution_count=15}\n    ![](06-sistemas-dinamicos-discretos_files/figure-html/cell-15-output-1.svg){}\n    :::\n    :::\n    \n    \n    La telaraña espiralea hacia el punto fijo estable $\\approx 0.643$.\n    :::\n\na.  Repetir la telaraña con $r = 3.3$ y comprobar que ahora aparece un **ciclo de periodo 2**.\n\n    :::{.callout-tip collapse=\"true\"}\n    ## Solución\n\n\n    ::: {#ef8f5790 .cell execution_count=15}\n    ``` {.julia .cell-code}\n    cobweb(x -> 3.3x * (1 - x), 0.1, 40, xlab = L\"x_n\", ylab = L\"x_{n+1}\")\n    ```\n    \n    ::: {.cell-output .cell-output-display execution_count=16}\n    ![](06-sistemas-dinamicos-discretos_files/figure-html/cell-16-output-1.svg){}\n    :::\n    :::\n    \n    \n    Para $r = 3.3$ el punto fijo se ha vuelto inestable ($|f'| = |2 - 3.3| = 1.3 > 1$) y la órbita se estabiliza en un cuadrado que alterna entre dos valores: la población oscila año sí, año no, entre un máximo y un mínimo (ciclo de periodo 2).\n    :::\n:::\n\n:::{#exr-diagrama-bifurcacion}\n**Diagrama de bifurcación y cascada de duplicación de periodo.** Al aumentar $r$ en el modelo logístico, los ciclos duplican su periodo ($1 \\to 2 \\to 4 \\to 8 \\to \\cdots$) hasta desembocar en el caos.\n\nConstruir el **diagrama de bifurcación** (atractor asintótico frente a $r$) para $r\\in[2.5, 4]$ y observar la cascada de duplicaciones y las ventanas de periodicidad.\n\n:::{.callout-note collapse=\"true\"}\n## Ayuda\nPara cada $r$, iterar la función muchas veces descartando el transitorio (p. ej. las primeras 300 iteraciones) y dibujar como puntos las siguientes (p. ej. 100). Usar `scatter` con marcadores muy pequeños.\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Solución\n\n::: {#f7d6c9df .cell execution_count=16}\n``` {.julia .cell-code}\nusing Plots, LaTeXStrings\nrs = range(2.5, 4.0, length = 1200)\nRvals = Float64[]; Xvals = Float64[]\nfor r in rs\n    x = 0.5\n    for _ in 1:300         # descartar transitorio\n        x = r * x * (1 - x)\n    end\n    for _ in 1:120         # registrar el atractor\n        x = r * x * (1 - x)\n        push!(Rvals, r); push!(Xvals, x)\n    end\nend\nscatter(Rvals, Xvals, ms = 0.4, msw = 0, color = :black, alpha = 0.3,\n    legend = false, xlab = L\"r\", ylab = L\"x^*\",\n    title = \"Diagrama de bifurcación del mapa logístico\")\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n![](06-sistemas-dinamicos-discretos_files/figure-html/cell-17-output-1.svg){}\n:::\n:::\n\n\nSe aprecia la cascada de duplicaciones de periodo (una rama, luego dos, cuatro, ocho…) que se acumula hacia $r_\\infty \\approx 3.5699$, a partir del cual el atractor es caótico, salpicado de **ventanas** de periodicidad (la más visible, el ciclo de periodo 3 cerca de $r = 3.83$).\n:::\n:::\n\n:::{#exr-feigenbaum}\n**La constante de Feigenbaum.** Los valores $r_k$ donde se producen las sucesivas duplicaciones de periodo se acumulan geométricamente: el cociente $\\delta_k = \\dfrac{r_k - r_{k-1}}{r_{k+1} - r_k}$ tiende a la **constante universal de Feigenbaum** $\\delta \\approx 4.6692$.\n\nEstimar numéricamente los primeros puntos de duplicación $r_1, r_2, r_3, r_4$ y calcular las aproximaciones de $\\delta$.\n\n:::{.callout-note collapse=\"true\"}\n## Ayuda\nLos primeros puntos de bifurcación se conocen analíticamente: $r_1 = 3$ (nace el 2-ciclo) y $r_2 = 1+\\sqrt6 \\approx 3.4495$ (nace el 4-ciclo). Los siguientes pueden localizarse numéricamente detectando dónde el periodo del atractor se duplica.\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Solución\n\n::: {#f9d42508 .cell execution_count=17}\n``` {.julia .cell-code}\n# Detecta el periodo del atractor para un r dado.\nfunction periodo(r; ntrans = 2000, ncheck = 2048, tol = 1e-5)\n    x = 0.5\n    for _ in 1:ntrans; x = r*x*(1-x); end\n    xs = [ (x = r*x*(1-x)) for _ in 1:ncheck ]\n    for p in (1, 2, 4, 8, 16, 32)\n        if all(abs(xs[end-i] - xs[end-i-p]) < tol for i in 0:p)\n            return p\n        end\n    end\n    return 0   # aperiódico / caótico\nend\n\n# Búsqueda por bisección del r donde el periodo pasa de p a 2p.\nfunction bifurca(plo, rlo, rhi)\n    for _ in 1:60\n        rm = (rlo + rhi)/2\n        periodo(rm) == plo ? (rlo = rm) : (rhi = rm)\n    end\n    (rlo + rhi)/2\nend\n\nr1 = bifurca(1, 2.9, 3.1)\nr2 = bifurca(2, 3.4, 3.5)\nr3 = bifurca(4, 3.54, 3.552)\nr4 = bifurca(8, 3.564, 3.569)\n(r1, r2, r3, r4)\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```\n(2.9980316137399807, 3.448760739988484, 3.5438053044368374, 3.564297510854689)\n```\n:::\n:::\n\n\n::: {#76e5c58a .cell execution_count=18}\n``` {.julia .cell-code}\nδ1 = (r2 - r1) / (r3 - r2)\nδ2 = (r3 - r2) / (r4 - r3)\n(delta_1 = δ1, delta_2 = δ2, valor_universal = 4.6692)\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n```\n(delta_1 = 4.742292511566254, delta_2 = 4.638083499176353, valor_universal = 4.6692)\n```\n:::\n:::\n\n\nLas estimaciones de $\\delta$ se aproximan progresivamente a la constante de Feigenbaum $\\approx 4.669$, que es **universal**: aparece en cualquier familia de mapas con un máximo cuadrático, y también en experimentos físicos reales de turbulencia y electrónica.\n:::\n:::\n\n:::{#exr-newton-discreto}\n**El método de Newton como sistema dinámico.** El método de Newton para resolver $g(x)=0$ es el sistema discreto $x_{n+1} = x_n - g(x_n)/g'(x_n)$. Aplicarlo a $g(x) = x^3 - 2x - 5$ (la ecuación históricamente usada por Newton), comprobar que su raíz real es un punto fijo superatractor ($f'(x^*)=0$) y observar la convergencia cuadrática desde $x_0 = 2$.\n\n:::{.callout-tip collapse=\"true\"}\n## Solución\n\n::: {#2396c38a .cell execution_count=19}\n``` {.julia .cell-code}\ng(x) = x^3 - 2x - 5\ngp(x) = 3x^2 - 2\nf(x) = x - g(x) / gp(x)\nxs = orbita(f, 2.0, 6)\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n```\n7-element Vector{Float64}:\n 2.0\n 2.1\n 2.094568121104185\n 2.094551481698199\n 2.0945514815423265\n 2.0945514815423265\n 2.0945514815423265\n```\n:::\n:::\n\n\n::: {#64534f0a .cell execution_count=20}\n``` {.julia .cell-code}\nraiz = xs[end]\nerrores = abs.(xs .- raiz)\n[(n = i-1, x = xs[i], error = errores[i]) for i in 1:length(xs)]\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n```\n7-element Vector{@NamedTuple{n::Int64, x::Float64, error::Float64}}:\n (n = 0, x = 2.0, error = 0.09455148154232651)\n (n = 1, x = 2.1, error = 0.005448518457673579)\n (n = 2, x = 2.094568121104185, error = 1.663956185860016e-5)\n (n = 3, x = 2.094551481698199, error = 1.5587264812211288e-10)\n (n = 4, x = 2.0945514815423265, error = 0.0)\n (n = 5, x = 2.0945514815423265, error = 0.0)\n (n = 6, x = 2.0945514815423265, error = 0.0)\n```\n:::\n:::\n\n\nEl número de decimales correctos se **duplica** en cada paso (convergencia cuadrática), reflejo de que en un punto fijo de Newton $f'(x^*) = g(x^*)g''(x^*)/g'(x^*)^2 = 0$: es un punto fijo superatractor. En seis iteraciones se alcanza la raíz $x^* \\approx 2.0946$ con precisión de máquina.\n:::\n:::\n\n## Ejercicios propuestos\n\n:::{#exr-propuesto-fibonacci}\n**Matemática financiera.** El sistema lineal de segundo orden $F_{n+1} = F_n + F_{n-1}$ (Fibonacci) puede escribirse en forma matricial. Calcular sus autovalores y comprobar que el cociente $F_{n+1}/F_n$ tiende al número áureo $\\varphi$.\n:::\n\n:::{#exr-propuesto-ricker}\n**Ecología.** Estudiar el modelo de Ricker $x_{n+1} = x_n e^{r(1 - x_n)}$: puntos fijos, estabilidad y diagrama de bifurcación en función de $r$.\n:::\n\n:::{#exr-propuesto-tienda}\nConstruir el diagrama de bifurcación del mapa de la tienda de campaña (*tent map*) $x_{n+1} = \\mu\\min(x_n, 1-x_n)$ y comparar la aparición del caos con la del mapa logístico.\n:::\n\n:::{#exr-propuesto-henon}\n**Sistema discreto en el plano.** Explorar el mapa de Hénon $x_{n+1} = 1 - a x_n^2 + y_n$, $y_{n+1} = b x_n$ con $a = 1.4$, $b = 0.3$ y dibujar su atractor extraño.\n:::\n\n",
    "supporting": [
      "06-sistemas-dinamicos-discretos_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}